export const InternshipHelperData = {
    'Location': [
        { name: 'Work From Home' },
        { name: 'Internships in Bangalore' },
        { name: 'Internships in Hyderabad' },
        { name: 'Internships in Mumbai' },
        { name: 'Internships in Chennai' },
        { name: 'Internships in Delhi-NCR' },
        { name: 'Internships in Pune' },
        { name: 'Internships IN Kolkata' },
        { name: 'Internships in Jaipur' },
        { name: 'International Internships' },
        { name: 'View all Internships' },
    ],
    'Profile': [
        { name: 'Computer Science Internships' },
        { name: 'Marketing Internships' },
        { name: 'Graphic design Internships' },
        { name: 'Finance Internships' },
        { name: 'HR Internships' },
        { name: 'Architecture Internships' },
        { name: 'Mechanical Internships' },
        { name: 'Law Internships' },
        { name: 'Digital Marketing Internships' },
        { name: 'Electronics Internships' },
        { name: 'Civil Internships' },
        { name: 'Content writing Internships' },
        { name: 'Campus Ambassador Program' },
        { name: 'View all Internships' },
    ],
    'Category': [
        { name: 'Enginnering Internships' },
        { name: 'MBA Internships' },
        { name: 'Graphic design Internships' },
        { name: 'Part-Time Internships' },
        { name: 'Humanities Internships' },
        { name: 'Science Internships' },
        { name: 'Internships with Job offer' },
        { name: 'Internships for Women' },
        { name: 'View all Internships' },
    ]
}

export const JobHelperData = {
    'Location': [
        { name: 'Work From Home' },
        { name: 'Jobs in Bangalore' },
        { name: 'Jobs in Hyderabad' },
        { name: 'Jobs in Mumbai' },
        { name: 'Jobs in Chennai' },
        { name: 'Jobs in Delhi-NCR' },
        { name: 'Jobs in Pune' },
        { name: 'Jobs IN Kolkata' },
        { name: 'Jobs in Jaipur' },
        { name: 'International Jobs' },
        { name: 'View all Jobs' },
    ],
    'Profile': [
        { name: 'Computer Science Jobs' },
        { name: 'Marketing Jobs' },
        { name: 'Graphic design Jobs' },
        { name: 'Finance Jobs' },
        { name: 'HR Jobs' },
        { name: 'Architecture Jobs' },
        { name: 'Mechanical Jobs' },
        { name: 'Law Jobs' },
        { name: 'Digital Marketing Jobs' },
        { name: 'Electronics Jobs' },
        { name: 'Civil Jobs' },
        { name: 'Content writing Jobs' },
        { name: 'Campus Ambassador Program' },
        { name: 'View all Jobs' },
    ],
    'Category': [
        { name: 'Enginnering Jobs' },
        { name: 'MBA Jobs' },
        { name: 'Graphic design Jobs' },
        { name: 'Part-Time Jobs' },
        { name: 'Humanities Jobs' },
        { name: 'Science Jobs' },
        { name: 'Jobs with Job offer' },
        { name: 'Jobs for Women' },
        { name: 'View all Jobs' },
    ]
}


export const TrainingHelperData = {
    'Most Popular': [
        { tag:'',name: 'Web Development' },
        { tag:'',name: 'Digital Marketing' },
        { tag:'',name: 'Programmig with Python' },
        { tag:'',name: 'AutoCAD' },
        { tag:'',name: 'Advanced Excel' },
        { tag:'',name: 'MachineLearning' },
        { tag:'',name: 'Android App Development' },
        { tag:'',name: 'Data Science' },
        { tag:'',name: 'Programming with C & C++' },
        { tag:'',name: 'Financial Modelling & Valuation' },
    ],
    'Programming': [
        { name: 'Programming With Python' },
        { name: 'Web Development' },
        { name: 'Ethical Hacking' },
        { name: 'Programming with C and c++' },
        { name: 'Android App Development' },
        { name: 'Core Java' },
        { name: 'React' },
        { name: 'Blockchain' },
        { name: 'Angular' },
        { name: 'Git & Github' },
        { name: 'How to Ace Coding Interviews' },
        { name: 'Data Structure & Algorithms' },
        { name: 'SAS Programming' },
        { name: 'Clinical Trials Analysis & Reporting' },
        { name: 'MATLAB' },
        { name: 'Software Testing' },
        { name: 'Node JS' },
        { name: 'Robotic Process Aotumation' },
        { name: 'PLC Programming' },
        { name: 'AR/VR' },
        { name: 'Voice APp Development' },
    ],
    'Business & Management': [
        { name: 'Digital Marketing' },
        { name: 'Advanced Excel' },
        { name: 'Financial Modelling and Valuation' },
        { name: 'Business Communication Skills' },
        { name: 'Stock Market Trading' },
        { name: 'Tally' },
        { name: 'Human Resource Management' },
        { name: 'Advanced Human Resouce Management' },
        { name: 'SQL for Data Analytics' },
        { name: 'Personal Finance 101' },
        { name: 'Business Analytics' },
        { name: 'Digital Marketing Specializzations' },
    ],
    'Core Engineering': [
        { name: 'AutoCAD' },
        { name: 'AutoCAD 3D' },
        { name: 'SOLIDWORKS' },
        { name: 'Advanced SOLIDWORKS' },
        { name: 'STAAD Pro' },
        { name: 'Fusion 360' },
        { name: 'Internet of Things' },
        { name: 'Ansys' },
        { name: '3D Printing' },
        { name: 'LabVIEW' },
        { name: 'Arduino' },
        { name: 'CATIA' },
        { name: 'MATLAB' },
        { name: 'Engineering Drawing' },
        { name: 'VLSI Design' },
        { name: 'Siemens NX' },
    ],
    'Data Science': [
        { name: 'Machine Learning' },
        { name: 'Data Science' },
        { name: 'Tableau' },
        { name: 'Deep Learning' },
        { name: 'SAS Programming' },
        { name: 'Clinical Trials Analysis & Reporting' },
        { name: 'Statistics for Data Science' },
        { name: 'Power BI' },
        { name: 'SQL for Data Analytics' },
        { name: 'Business Analytics' },
        { name: 'Data Science Specializations' },
        { name: 'Natural Language Processing' },
    ],
    'Design': [
        { name: 'Graphic Design' },
        { name: 'UI/UX Design' },
        { name: 'Video Editing' },
        { name: 'Animation' },
        { name: 'WordPress' },
        { name: 'Digital Art' },
        { name: 'Colour Theory' },
    ],
    'Creative Arts': [
        { name: 'Creative Writing' },
        { name: 'Learn Guide in 30 Days' },
        { name: 'Photography' },
        { name: 'Calligraphy' },
        { name: 'Acting' },
    ],
    'Language': [
        { name: 'French' },
    ],
    'Career Development': [
        { name: 'Business Communication Skills' },
        { name: 'Internship & Job Preparation' },
        { name: 'How to Ace Coding Interviews' },
        { name: 'Interview Preparation' },
    ],
    'Architecture': [
        { name: 'AutoCAD' },
        { name: 'AutoCAD 3D' },
        { name: 'Revit' },
    ],
    'Specializations': [
        { name: 'Digital Marketing Specialzations' },
        { name: 'Data Science Specialzations' },
    ],
}


export const UserHelperData = {
    'Contact':[
        {name:'Contact as Employers',url:'/chosen=contact-as-employers'},
        {name:'Contact as Job seekers',url:'/chosen=contact-as-job-seekers'},
    ],
    'Login':[
        {name:'Login as Employers',url:'/chosen=login-as-employers'},
        {name:'Login as Job seekers',url:'/chosen=login-as-job-seekers'},
    ],
    'Register':[
        {name:'Register as Employers',url:'/chosen=register-as-employers'},
        {name:'Register as Job seekers',url:'/chosen=register-as-job-seekers'},
    ],
}

export const SkillsData=[
    'Java',"JavaScript",'Python','Ruby',"GoLang",'C','C#','C++'
]